# This is a basic workflow to help you get started with Actions

name: Check GCP action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  Get_OIDC_Access_Token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to GCP"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: "projects/460967600907/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider"
          service_account: "iam-lab-7-target@gcp-labs-tsrkga5t.iam.gserviceaccount.com"

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Run gcloud commands
        run: |
          gcloud config set project gcp-labs-tsrkga5t
          gcloud auth list
          gcloud projects list
          gcloud secrets list
